import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from "next/script";

export default function Home() {
  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

        </Head>
        <Script
            id="evo"
            src="https://gammixbeg.uat1.evo-test.com/frontend/evo/r2/js/iframe.js"
            strategy="beforeInteractive"
            onError={() => console.log('Error')}
            onLoad={() => {
              console.log('Load')
            }}
        />

        <Script
            id="evo-game" strategy="lazyOnload"
            src="https://gammixbeg.uat1.evo-test.com/frontend/evo/r2/js/iframe.js"
        >
          {`EvolutionGaming.init({
            url: "https://gammixbeg.uat1.evo-test.com/entry?params=QVVUSF9UT0tFTj1wemczeTJ1NW9uNWFieWJ6cWthNXQzd2N2NW5xZHBybDY2YmYwNjJlCmNhdGVnb3J5PWJhY2NhcmF0X3NpY2JvCnNpdGU9MQ",
            topBar: 1,
            allowFullscreen: true
          })`}
        </Script>

      </div>
  )
}